// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: grpc/game_world.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoopNumber int32 `protobuf:"varint,1,opt,name=loop_number,json=loopNumber,proto3" json:"loop_number,omitempty"`
	Level      int32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *ItemRequest) Reset() {
	*x = ItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_game_world_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRequest) ProtoMessage() {}

func (x *ItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_game_world_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRequest.ProtoReflect.Descriptor instead.
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return file_grpc_game_world_proto_rawDescGZIP(), []int{0}
}

func (x *ItemRequest) GetLoopNumber() int32 {
	if x != nil {
		return x.LoopNumber
	}
	return 0
}

func (x *ItemRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_game_world_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_game_world_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_grpc_game_world_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_grpc_game_world_proto protoreflect.FileDescriptor

var file_grpc_game_world_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x22, 0x44, 0x0a, 0x0b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x6f, 0x6f, 0x70, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x6f, 0x6f, 0x70, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x1a, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x32, 0x47, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x57, 0x6f, 0x72, 0x6c,
	0x64, 0x12, 0x3a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x16, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x00, 0x42, 0x2a, 0x5a,
	0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x72, 0x62, 0x61,
	0x6e, 0x79, 0x65, 0x74, 0x69, 0x2f, 0x67, 0x6f, 0x2d, 0x68, 0x65, 0x72, 0x6f, 0x2d, 0x67, 0x61,
	0x6d, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_grpc_game_world_proto_rawDescOnce sync.Once
	file_grpc_game_world_proto_rawDescData = file_grpc_game_world_proto_rawDesc
)

func file_grpc_game_world_proto_rawDescGZIP() []byte {
	file_grpc_game_world_proto_rawDescOnce.Do(func() {
		file_grpc_game_world_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_game_world_proto_rawDescData)
	})
	return file_grpc_game_world_proto_rawDescData
}

var file_grpc_game_world_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_game_world_proto_goTypes = []interface{}{
	(*ItemRequest)(nil), // 0: gameworld.ItemRequest
	(*Item)(nil),        // 1: gameworld.Item
}
var file_grpc_game_world_proto_depIdxs = []int32{
	0, // 0: gameworld.GameWorld.GetRandomItem:input_type -> gameworld.ItemRequest
	1, // 1: gameworld.GameWorld.GetRandomItem:output_type -> gameworld.Item
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_game_world_proto_init() }
func file_grpc_game_world_proto_init() {
	if File_grpc_game_world_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_game_world_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_game_world_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_game_world_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_game_world_proto_goTypes,
		DependencyIndexes: file_grpc_game_world_proto_depIdxs,
		MessageInfos:      file_grpc_game_world_proto_msgTypes,
	}.Build()
	File_grpc_game_world_proto = out.File
	file_grpc_game_world_proto_rawDesc = nil
	file_grpc_game_world_proto_goTypes = nil
	file_grpc_game_world_proto_depIdxs = nil
}
